### PR TITLE
Change from nruns to targetted test duration

### PR DESCRIPTION
**Pull request by slopp**
also quick fix to recorder to end on ws_close

### CODE REVIEW

**Comment by jcheng5** [comment]
This lets each "thread" run for `--duration` seconds. But now that the threads have varying startup times, shouldn't it be that the clock only starts counting after all the threads have started, and then all threads are stopped at the same time?

**Comment by slopp** [comment]
@jcheng5 - do you mind double checking the logic, I think I got it right this time around.

**Comment by jcheng5** [comment]
Are we interested in all the jobs--during warmup, during steady-state, and during shutdown? Or only the steady-state? (Like flying laps in racing)

**Comment by jcheng5** [comment]
Also this might be nice, so you can specify a duration of `5m` instead of `300` https://www.npmjs.com/package/parse-duration

**Comment by slopp** [comment]
>  Are we interested in all the jobs--during warmup, during steady-state, and during shutdown?

Most likely we are interested in steady-state, but I'd vote to leave any 'trimming' in the analysis functions in `shinyloadtest`, doesn't seem like it should be the job of `playback`

**Pull request merged**
